# -*- coding: utf-8 -*-
"""Untitled64.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HgKCUhnxS6QgoWrXH1BfjR3zobsY2dpw
"""

# app.py – Streamlit + Seaborn demo that runs offline in the Playground
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from io import StringIO

# ---------- local copy of Seaborn's tips dataset ----------
_TIPS_CSV = """
total_bill,tip,sex,smoker,day,time,size
16.99,1.01,Female,No,Sun,Dinner,2
10.34,1.66,Male,No,Sun,Dinner,3
21.01,3.50,Male,No,Sun,Dinner,3
23.68,3.31,Male,No,Sun,Dinner,2
24.59,3.61,Female,No,Sun,Dinner,4
25.29,4.71,Male,No,Sun,Dinner,4
8.77,2.00,Male,No,Sun,Dinner,2
26.88,3.12,Male,No,Sun,Dinner,4
15.04,1.96,Male,No,Sun,Dinner,2
14.78,3.23,Male,No,Sun,Dinner,2
20.65,3.35,Male,No,Sat,Dinner,3
17.92,4.08,Male,No,Sat,Dinner,2
20.29,2.75,Female,No,Sat,Dinner,2
15.77,2.23,Female,No,Sat,Dinner,2
39.42,7.58,Male,No,Sat,Dinner,4
19.82,3.18,Male,No,Sat,Dinner,2
17.81,2.34,Male,No,Sat,Dinner,4
13.37,2.00,Male,No,Sat,Dinner,2
12.69,2.00,Male,No,Sat,Dinner,2
21.70,4.30,Male,No,Sat,Dinner,2
18.29,3.00,Male,No,Sat,Dinner,2
"""
tips = pd.read_csv(StringIO(_TIPS_CSV.strip()))

# ---------- Streamlit layout ----------
st.set_page_config(page_title="Tips demo", layout="centered")
st.title("Seaborn × Streamlit: *tips* dataset")

plot_kind = st.sidebar.selectbox(
    "Choose a plot",
    ("Scatter: total_bill vs tip",
     "Box: tip by day",
     "Histogram: total_bill")
)

# ---------- build figure ----------
fig, ax = plt.subplots(figsize=(7, 4))
sns.set_theme(style="whitegrid")

if plot_kind.startswith("Scatter"):
    sns.scatterplot(
        data=tips, x="total_bill", y="tip",
        hue="sex", style="smoker", s=100, ax=ax
    )
    ax.set_title("Tip vs. Total Bill")

elif plot_kind.startswith("Box"):
    sns.boxplot(
        data=tips, x="day", y="tip",
        hue="smoker", ax=ax
    )
    ax.set_title("Tip by Day (Smoker vs Non-smoker)")

else:  # Histogram
    sns.histplot(
        tips["total_bill"], kde=True, bins=12, ax=ax
    )
    ax.set_title("Distribution of Total Bills")

st.pyplot(fig)
st.markdown("#### Data preview")
st.dataframe(tips)